---
  - name: Create Mount points
    include_tasks: create_mounts.yml
  - name: Create Bridge Interface
    include_tasks: create_bridge.yml
  - name: Install required softwares
    include_tasks: install_packages.yml
  - name: Deploy Jenkins
    when: "{{ Jenkins }} == true"
    include_tasks: docker.yml